name: Lint
on:
  pull_request:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install packages
        run: yarn install --immutable

      - name: Lint
        uses: github/super-linter/slim@v4.9.7
        env:
          VALIDATE_ALL_CODEBASE: false
          LINTER_RULES_PATH: /
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_DEFAULT_STYLE: prettier
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          TYPESCRIPT_DEFAULT_STYLE: prettier
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_YAML: false
          VALIDATE_HTML: false
